version: '2'
services:
  db:
    image: hamzaisaeed/postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
  kafka:
    image: hamzaisaeed/kafka:latest
    environment:
      ADVERTISED_HOST: 127.0.0.1
      ADVERTISED_PORT: 9092
    ports:
     - "2181:2181"
     - "9092:9092"